"use client";

import { useState } from "react";
import Dropdown from "@/components/ui/Dropdown";

const REPORTS = [
  {
    title: "Monthly Billing Summary",
    period: "February 2026",
    generatedBy: "Accounting User",
    format: "PDF",
    status: "Ready",
  },
  {
    title: "Outstanding Invoices Report",
    period: "February 2026",
    generatedBy: "Accounting User",
    format: "Excel",
    status: "Ready",
  },
  {
    title: "Branch Revenue Snapshot",
    period: "February 2026",
    generatedBy: "Accounting User",
    format: "PDF",
    status: "Draft",
  },
];

export default function AccountingReportsPage() {
  const [branch, setBranch] = useState("all");

  return (
    <>
      <div className="page">
        <div className="header">
          <div>
            <h1>Accounting Reports</h1>
            <p>Generate billing summaries, payment reports, and financial snapshots.</p>
          </div>

          <div className="actions">
            <Dropdown
              options={[
                { label: "All Branches", value: "all" },
                { label: "Marikina", value: "marikina" },
                { label: "Pateros", value: "pateros" },
              ]}
              value={branch}
              onChange={setBranch}
            />

            <button type="button" className="primaryButton">
              Generate New Report
            </button>
          </div>
        </div>

        <div className="contentGrid">
          <div className="panel">
            <div className="panelHeader">
              <h3>Available Reports</h3>
              <button type="button">Export All</button>
            </div>

            <div className="reportList">
              {REPORTS.map((report, index) => (
                <div key={index} className="reportCard">
                  <div className="reportTop">
                    <div>
                      <strong>{report.title}</strong>
                      <p>{report.period}</p>
                    </div>

                    <span
                      className={
                        report.status === "Ready" ? "status ready" : "status draft"
                      }
                    >
                      {report.status}
                    </span>
                  </div>

                  <div className="meta">
                    <span>Generated by: {report.generatedBy}</span>
                    <span>Format: {report.format}</span>
                  </div>

                  <div className="cardActions">
                    <button type="button" className="secondaryButton">
                      Preview
                    </button>
                    <button type="button" className="primaryButton smallButton">
                      Download
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="panel">
            <div className="panelHeader">
              <h3>Report Generator</h3>
            </div>

            <div className="generatorForm">
              <div className="field">
                <label>Report Type</label>
                <input value="Monthly Billing Summary" readOnly />
              </div>

              <div className="field">
                <label>Coverage Period</label>
                <input value="February 2026" readOnly />
              </div>

              <div className="field">
                <label>Output Format</label>
                <input value="PDF / Excel" readOnly />
              </div>

              <button type="button" className="primaryButton fullWidth">
                Create Report
              </button>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .page {
          display: flex;
          flex-direction: column;
          gap: 28px;
        }

        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          gap: 24px;
        }

        h1 {
          margin: 0;
          font-size: 24px;
          color: #1f2937;
        }

        p {
          margin: 6px 0 0;
          font-size: 14px;
          color: #4b5563;
        }

        h3 {
          margin: 0;
          color: #1f2937;
          font-size: 15px;
          font-weight: 700;
        }

        .actions {
          display: flex;
          gap: 12px;
          flex-wrap: wrap;
          align-items: center;
        }

        .contentGrid {
          display: grid;
          grid-template-columns: 1.2fr 0.8fr;
          gap: 20px;
        }

        .panel {
          background: #ffffff;
          border: 1px solid #e5e7eb;
          border-radius: 18px;
          padding: 20px;
        }

        .panelHeader {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 12px;
          margin-bottom: 16px;
        }

        .panelHeader button {
          border: none;
          background: transparent;
          color: #4b5563;
          font-size: 12px;
          font-weight: 700;
          cursor: pointer;
        }

        .reportList {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .reportCard {
          background: #f8fafc;
          border: 1px solid #e5e7eb;
          border-radius: 16px;
          padding: 16px;
        }

        .reportTop {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          gap: 14px;
          margin-bottom: 12px;
        }

        .reportTop strong {
          display: block;
          font-size: 14px;
          color: #111827;
        }

        .reportTop p {
          margin: 4px 0 0;
          font-size: 12px;
          color: #4b5563;
        }

        .meta {
          display: flex;
          flex-direction: column;
          gap: 4px;
          margin-bottom: 14px;
        }

        .meta span {
          font-size: 12px;
          color: #4b5563;
        }

        .status {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          min-width: 72px;
          padding: 6px 10px;
          border-radius: 999px;
          font-size: 11px;
          font-weight: 700;
        }

        .status.ready {
          background: #ecfdf5;
          color: #047857;
        }

        .status.draft {
          background: #fff7ed;
          color: #c2410c;
        }

        .cardActions {
          display: flex;
          gap: 10px;
        }

        .primaryButton,
        .secondaryButton {
          height: 44px;
          border-radius: 12px;
          padding: 0 16px;
          font-size: 13px;
          font-weight: 700;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .primaryButton {
          border: none;
          background: #080026;
          color: #ffffff;
        }

        .primaryButton:hover {
          background: #14004a;
        }

        .secondaryButton {
          border: 1px solid #d1d5db;
          background: #ffffff;
          color: #1f2937;
        }

        .secondaryButton:hover {
          border-color: #9ca3af;
        }

        .smallButton {
          height: 38px;
        }

        .generatorForm {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .field {
          display: flex;
          flex-direction: column;
          gap: 8px;
        }

        .field label {
          font-size: 12px;
          font-weight: 700;
          color: #374151;
        }

        .field input {
          height: 46px;
          border: 1px solid #d8d8d8;
          border-radius: 14px;
          padding: 0 14px;
          font-size: 13px;
          color: #1f2937;
          background: #ffffff;
          outline: none;
        }

        .fullWidth {
          width: 100%;
        }

        @media (max-width: 980px) {
          .header {
            flex-direction: column;
          }

          .contentGrid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </>
  );
}